version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sweethome-php
    container_name: sweethome_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    networks:
      - sweethome

  web:
    image: nginx:1.25-alpine
    container_name: sweethome_web
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sweethome

networks:
  sweethome:
    driver: bridge
